version: '3'
services:
  postgres-sql:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: yiecheverria@mail.com
      PGADMIN_DEFAULT_PASSWORD: 2700
    ports:
      - 5050:80
  books-service:
    image: yiecheverria/correcion:1.0
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://postgres-sql:5432/distribuida
    deploy:
      replicas: 1
    ports:
      - "7001:7001"